name: sqt-skoltech
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cycler=0.10.0
  - freetype=2.10.4
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.1.0
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - ncurses=6.2
  - numpy=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=8.1.2
  - pip=21.0.1
  - pyparsing=2.4.7
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - qutip=4.5.3
  - readline=8.1
  - scipy=1.6.2
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.35.3
  - tk=8.6.10
  - tornado=6.1
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
